// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUqq77yeydKUJSvRwsYFXglJ_tlCEbwC0',
    appId: '1:730707470787:web:8dedf2cce6f35b408ef576',
    messagingSenderId: '730707470787',
    projectId: 'project-donation-system',
    authDomain: 'project-donation-system.firebaseapp.com',
    storageBucket: 'project-donation-system.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_EZ2MeH4STxGzNBvUy6QoK3Ngi6zNRAE',
    appId: '1:730707470787:android:8cea772a0da8d9568ef576',
    messagingSenderId: '730707470787',
    projectId: 'project-donation-system',
    storageBucket: 'project-donation-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSVHduQo3csCf7IFeulirhlfZwXQ143sE',
    appId: '1:730707470787:ios:b1d12a2c2c68bd278ef576',
    messagingSenderId: '730707470787',
    projectId: 'project-donation-system',
    storageBucket: 'project-donation-system.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSVHduQo3csCf7IFeulirhlfZwXQ143sE',
    appId: '1:730707470787:ios:b1d12a2c2c68bd278ef576',
    messagingSenderId: '730707470787',
    projectId: 'project-donation-system',
    storageBucket: 'project-donation-system.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUqq77yeydKUJSvRwsYFXglJ_tlCEbwC0',
    appId: '1:730707470787:web:7601df1535e9e8748ef576',
    messagingSenderId: '730707470787',
    projectId: 'project-donation-system',
    authDomain: 'project-donation-system.firebaseapp.com',
    storageBucket: 'project-donation-system.appspot.com',
  );
}
